apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-jenkins-astrovilla-app
  labels:
    app: kubernetes-jenkins-astrovilla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-jenkins-astrovilla
  template:
    metadata:
      labels:
        app: kubernetes-jenkins-astrovilla
    spec:
      containers:
      - name: kubernetes-jenkins-astrovilla
        image: 18.217.12.100:8021/nodejs-app:1
        ports:
        - containerPort: 4444
